"use strict";
let personName = 'John';
console.log(personName);
let age = 20;
console.log(age);
let hasPets = true;
console.log(hasPets);
let otherPerson;
otherPerson = 25;
console.log(otherPerson);
let hobbies = ["Cook", "Play"];
console.log(hobbies);
